# Default config for Artipie docker image
meta:
  storage:
    type: fs
    path: /var/artipie/repo
  credentials:
    -
      type: env
    -
      type: github
    -
      type: file
      path: _credentials.yml
  layout: org
